monolog:
    handlers:
        main:
            type: error_log
            level: debug
            channels: ["!event"]
        console:
            type:   console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
